spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/clouddb01
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
mybatis:
    config-localhost: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.hkctp.springcloud.entities
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
    
eureka:
    client:     
        service-url:    
            defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: product-8001.com
        prefer-ip-address: true
        
info:
    app.name:   hkctp-microservicecloud-springcloudconfig01
    company.name: www.hkctp.com.hk
    build.artifactId: ${project.artifactId}
    build.version: ${project.version}
    
---
server:
    port: 8001
spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
mybatis:
    config-localhost: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.hkctp.springcloud.entities
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
    
eureka:
    client:     
        service-url:    
            defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: product-8001.com
        prefer-ip-address: true
        
info:
    app.name:   hkctp-microservicecloud-springcloudconfig01
    company.name: www.hkctp.com.hk
    build.artifactId: ${project.artifactId}
    build.version: ${project.version}